.TH COMM 1 "GNU Text Utilities" "FSF" \" -*- nroff -*-
.SH NAME
comm \- compare two sorted files line by line
.SH SYNOPSIS
.B comm
[\-123] [\-\-help] [\-\-version] file1 file2
.SH DESCRIPTION
This documentation is no longer being maintained and may be inaccurate
or incomplete.  The Texinfo documentation is now the authoritative source.
.PP
This manual page
documents the GNU version of
.BR comm .
.B comm
prints lines that are common, and lines that are unique, to two input
files.  The two files must be sorted before
.B comm
can be used.  The file name `\-' means the standard input.
.PP
With no options,
.B comm
produces three column output.  Column
one contains lines unique to
.IR file1 ,
column two contains
lines unique to
.IR file2 ,
and column three contains lines common to both files.
.SS OPTIONS
.PP
The options
.IR \-1 ,
.IR \-2 ,
and
.I \-3
suppress printing of the corresponding columns.
.TP
.I "\-\-help"
Print a usage message and exit with a status code indicating success.
.TP
.I "\-\-version"
Print version information on standard output then exit.
