@DATABASE "gg:doc/NDK/Guide/Include/clib/render_protos.h"
@MASTER   "gg:os-include/clib/render_protos.h"
@REMARK   This file was created by ADtoHT 2.1 on 06-Jan-13 19:11:58
@REMARK   Do not edit
@REMARK   ADtoHT is © 1993-1995 Christian Stieber

@NODE MAIN "clib/render_protos.h"
@TOC "gg:doc/NDK/Guide/TOC/MAIN"

@{"clib/render_protos.h" LINK File}

@ENDNODE
@NODE File "clib/render_protos.h"
#ifndef CLIB_RENDER_PROTOS_H
#define CLIB_RENDER_PROTOS_H
/*
**      $VER: render_protos.h v29.1 (19.5.99)
**
**      C prototype definitions
**
**      © TEK neoscientists
*/

#ifndef GRAPHICS_GFX_H
#include <@{"graphics/gfx.h" LINK "gg:doc/NDK/Guide/Include/graphics/gfx.h/File"}>
#endif

#ifndef UTILITY_HOOKS_H
#include <@{"utility/hooks.h" LINK "gg:doc/NDK/Guide/Include/utility/hooks.h/File"}>
#endif

#ifndef UTILITY_TAGITEM_H
#include <@{"utility/tagitem.h" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File"}>
#endif

/*   private functions: */

void    TurboFillMem( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49},@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52},@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} );
void    TurboCopyMem( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49},@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49},@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   *CreateHistogramPointerArray( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   CountHistogram( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   GetPaletteAttrs( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52});
void    RemapArrayA(@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *source, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55} width, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55} height, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *dest, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *pentab, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    RemapArray(@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *source, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55} width, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55} height, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *dest, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *pentab, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );


/*   public functions:  */

@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateRMHandlerA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 26}( @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateRMHandler" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 31}( @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"DeleteRMHandler" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 35}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"AllocRenderMem" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 39}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );
void    @{"FreeRenderMem" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 43}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"AllocRenderVec" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 47}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );
void    @{"FreeRenderVec" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 51}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"AllocRenderVecClear" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 329}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );

@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateHistogramA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 55}( @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateHistogram" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 60}( @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"DeleteHistogram" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 64}(@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49});
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"QueryHistogram" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 68}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddRGB" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 72}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddRGBImageA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 76}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddRGBImage" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 81}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddChunkyImageA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 85}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddChunkyImage" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 90}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"ExtractPaletteA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 94}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"ExtractPalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 99}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"RenderA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 103}( @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"Render" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 108}( @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

void    @{"Planar2ChunkyA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 112}( @{"PLANEPTR" LINK "gg:doc/NDK/Guide/Include/graphics/gfx.h/File" 44} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
void    @{"Planar2Chunky" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 117}( @{"PLANEPTR" LINK "gg:doc/NDK/Guide/Include/graphics/gfx.h/File" 44} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"Chunky2RGBA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 121}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"Chunky2RGB" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 126}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"Chunky2BitMapA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 130}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct BitMap" LINK "gg:doc/NDK/Guide/Include/graphics/gfx.h/File" 46} *, UWORD, UWORD, struct TagItem * );
void    @{"Chunky2BitMap" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 135}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct BitMap" LINK "gg:doc/NDK/Guide/Include/graphics/gfx.h/File" 46} *, UWORD, UWORD, Tag, ... );

@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateScaleEngineA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 139}( @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateScaleEngine" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 144}( @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"DeleteScaleEngine" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 148}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"ScaleA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 152}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"Scale" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 157}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"ConvertChunkyA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 161}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"ConvertChunky" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 166}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"CreatePenTableA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 170}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
void    @{"CreatePenTable" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 175}( @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreatePaletteA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 179}( @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreatePalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 184}( @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"DeletePalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 188}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
void    @{"ImportPaletteA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 192}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
void    @{"ImportPalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 197}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"ExportPaletteA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 201}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
void    @{"ExportPalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 206}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"FlushPalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 218}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"SortPaletteA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 222}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"SortPalette" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 227}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"CountRGB" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 210}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );
@{"LONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 51}    @{"BestPen" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 214}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} );

@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddHistogramA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 231}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"AddHistogram" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 236}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

@{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}   @{"ScaleOrdinate" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 240}( @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55} );

@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateMapEngineA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 244}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}    @{"CreateMapEngine" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 249}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"DeleteMapEngine" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 253}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49} );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"MapRGBArrayA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 257}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"MapRGBArray" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 262}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"MapChunkyArrayA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 284}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}   @{"MapChunkyArray" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 289}( @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

@{"LONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 51}    @{"RGBArrayDiversityA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 266}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} * );
@{"LONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 51}    @{"RGBArrayDiversity" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 271}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

@{"LONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 51}    @{"ChunkyArrayDiversityA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 275}(@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
@{"LONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 51}    @{"ChunkyArrayDiversity" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 280}(@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"APTR" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 49}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

void    @{"InsertAlphaChannelA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 293}(@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"InsertAlphaChannel" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 298}(@{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"ExtractAlphaChannelA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 302}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"ExtractAlphaChannel" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 307}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UBYTE" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 62} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"ApplyAlphaChannelA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 311}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"ApplyAlphaChannel" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 316}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"MixRGBArrayA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 320}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"MixRGBArray" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 325}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"CreateAlphaArrayA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 333}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"CreateAlphaArray" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 338}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"MixAlphaChannelA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 342}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"MixAlphaChannel" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 347}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );
void    @{"TintRGBArrayA" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 351}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"struct TagItem" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 32} *);
void    @{"TintRGBArray" LINK "gg:doc/NDK/Guide/Include/inline/render.h/File" 356}(@{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52}, @{"UWORD" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 55}, @{"ULONG" LINK "gg:doc/NDK/Guide/Include/exec/types.h/File" 52} *, @{"Tag" LINK "gg:doc/NDK/Guide/Include/utility/tagitem.h/File" 30}, ... );

#endif
@ENDNODE
