#pragma libcall XtBase XtAppInitialize 1e 32DCB1A9809
#pragma libcall XtBase XrmGetResource 24 CBA9805
#pragma libcall XtBase XrmGetStringDatabase 2a 801
#pragma libcall XtBase XrmMergeDatabases 30 9802
#pragma libcall XtBase XrmInitialize 36 0
#pragma libcall XtBase XrmGetFileDatabase 3c 801
#pragma libcall XtBase XrmDestroyDatabase 42 801
#pragma libcall XtBase XrmPutStringResource 48 A9803
#pragma libcall XtBase XrmPutResource 4e BA9804
#pragma libcall XtBase XtDatabase 54 801
#pragma libcall XtBase XtShellStrings 5a 0
#pragma libcall XtBase XtWindow 60 801
#pragma libcall XtBase XtOpenDisplay 66 2D1CBA9808
#pragma libcall XtBase XtCloseDisplay 6c 801
#pragma libcall XtBase XtParseTranslationTable 72 801
#pragma libcall XtBase XtAppAddActions 78 19803
#pragma libcall XtBase XtAppNextEvent 7e 9802
#pragma libcall XtBase XtAppAddTimeOut 84 A91804
#pragma libcall XtBase XtAppMainLoop 8a 801
#pragma libcall XtBase XtAppCreateShell 90 1CBA9806
#pragma libcall XtBase XtGetApplicationResources 96 2B1A9806
#pragma libcall XtBase XtDispatchEvent 9c 801
#pragma libcall XtBase XtRealizeWidget a2 801
#pragma libcall XtBase XtToolkitInitialize a8 0
#pragma libcall XtBase XtCreateApplicationContext ae 0
#pragma libcall XtBase XtStrings b4 0
#pragma libcall XtBase XtAddEventHandler ba A921805
#pragma libcall XtBase XtAddCallback c0 BA9804
#pragma libcall XtBase XtAddGrab c6 21803
#pragma libcall XtBase XtAppPending cc 801
#pragma libcall XtBase XtAppProcessEvent d2 1802
#pragma libcall XtBase XtFree d8 801
#pragma libcall XtBase XtGetValues de 19803
#pragma libcall XtBase XtMalloc e4 101
#pragma libcall XtBase XtManageChild ea 801
#pragma libcall XtBase XtManageChildren f0 1802
#pragma libcall XtBase XtRemoveGrab f6 801
#pragma libcall XtBase XtSetValues fc 19803
#pragma libcall XtBase XtUnmanageChild 102 801
#pragma libcall XtBase XtVaCreateManagedWidget 108 1BA9805
#pragma libcall XtBase XtVaCreateWidget 10e 1BA9805
#pragma libcall XtBase XtVaSetValues 114 19803
#pragma libcall XtBase XtWarning 11a 801
#pragma libcall XtBase XtWidgetToApplicationContext 120 801
#pragma libcall XtBase XtDestroyWidget 126 801
#pragma libcall XtBase XtGetApplicationNameAndClass 12c A9803
#pragma libcall XtBase XtGetGC 132 91803
#pragma libcall XtBase XtWindowOfObject 138 801
#pragma libcall XtBase XtRealloc 13e 0
#pragma libcall XtBase XtRemoveCallback 144 0
#pragma libcall XtBase XtMoveWidget 14a 0
#pragma libcall XtBase XtCalloc 150 0
#pragma libcall XtBase XtAugmentTranslations 156 0
#pragma libcall XtBase XtPopup 15c 0
#pragma libcall XtBase XtCallCallbacks 162 0
#pragma libcall XtBase XtNameToWidget 168 0
#pragma libcall XtBase XtSetTypeConverter 16e 0
#pragma libcall XtBase XtParseAcceleratorTable 174 0
#pragma libcall XtBase XtInstallAccelerators 17a 0
#pragma libcall XtBase XtCallActionProc 180 0
#pragma libcall XtBase XtName 186 0
#pragma libcall XtBase XtSetKeyboardFocus 18c 0
#pragma libcall XtBase XtRemoveEventHandler 192 0
#pragma libcall XtBase XtReleaseGC 198 0
#pragma libcall XtBase XtResizeWidget 19e 0
#pragma libcall XtBase XtPopdown 1a4 801
#pragma libcall XtBase XtRemoveTimeOut 1aa 101
#pragma libcall XtBase XtGetSelectionValue 1b0 0
#pragma libcall XtBase XtSetSensitive 1b6 0
#pragma libcall XtBase XtInstallAllAccelerators 1bc 0
#pragma libcall XtBase XtCreateWidget 1c2 0
#pragma libcall XtBase XtStringConversionWarning 1c8 0
#pragma libcall XtBase XtCreateManagedWidget 1ce 0
#pragma libcall XtBase XtAppAddConverter 1d4 0
#pragma libcall XtBase XtVaGetValues 1da 0
#pragma libcall XtBase XtTranslateCoords 1e0 0
#pragma libcall XtBase XtCreatePopupShell 1e6 0
#pragma libcall XtBase XtOverrideTranslations 1ec 0
#pragma libcall XtBase applicationShellWidgetClass 1f2 0
#pragma libcall XtBase _XtInherit 1f8 0
#pragma libcall XtBase XSetCommand 1fe 1A9804
#pragma libcall XtBase XMapWindow 204 9802
#pragma libcall XtBase XSetWindowBorder 20a 19803
#pragma libcall XtBase XSetIconName 210 A9803
#pragma libcall XtBase XSetNormalHints 216 A9803
#pragma libcall XtBase XSetClassHint 21c A9803
#pragma libcall XtBase XSetWMHints 222 A9803
#pragma libcall XtBase XSetErrorHandler 228 801
#pragma libcall XtBase XSync 22e 1802
#pragma libcall XtBase XGetErrorText 234 A9803
#pragma libcall XtBase XDefaultScreenOfDisplay 23a 801
#pragma libcall XtBase XWarpPointer 240 654321A9809
#pragma libcall XtBase XmAddProtocolCallback 246 0
#pragma libcall XtBase XmCommandGetChild 24c 0
#pragma libcall XtBase XmCreateCommand 252 0
#pragma libcall XtBase XmCreateDialogShell 258 0
#pragma libcall XtBase XmCreateErrorDialog 25e 0
#pragma libcall XtBase XmCreateFileSelectionDialog 264 0
#pragma libcall XtBase XmCreateForm 26a 0
#pragma libcall XtBase XmCreateFrame 270 0
#pragma libcall XtBase XmCreateLabel 276 0
#pragma libcall XtBase XmCreateLabelGadget 27c 0
#pragma libcall XtBase XmCreateMainWindow 282 0
#pragma libcall XtBase XmCreateMenuBar 288 0
#pragma libcall XtBase XmCreateOptionMenu 28e 0
#pragma libcall XtBase XmCreatePulldownMenu 294 0
#pragma libcall XtBase XmCreatePushButton 29a 0
#pragma libcall XtBase XmCreatePushButtonGadget 2a0 0
#pragma libcall XtBase XmCreateRadioBox 2a6 0
#pragma libcall XtBase XmCreateRowColumn 2ac 0
#pragma libcall XtBase XmCreateScrolledText 2b2 0
#pragma libcall XtBase XmCreateToggleButton 2b8 0
#pragma libcall XtBase XmCreateToggleButtonGadget 2be 0
#pragma libcall XtBase XmInternAtom 2c4 0
#pragma libcall XtBase XmListAddItemUnselected 2ca 0
#pragma libcall XtBase XmListDeletePos 2d0 0
#pragma libcall XtBase XmMainWindowSetAreas 2d6 0
#pragma libcall XtBase XmMessageBoxGetChild 2dc 0
#pragma libcall XtBase XmStringCreate 2e2 0
#pragma libcall XtBase XmStringCreateLtoR 2e8 0
#pragma libcall XtBase XmStringFree 2ee 0
#pragma libcall XtBase XmStringGetLtoR 2f4 0
#pragma libcall XtBase XmTextGetLastPosition 2fa 0
#pragma libcall XtBase XmTextGetString 300 0
#pragma libcall XtBase XmTextInsert 306 0
#pragma libcall XtBase XmTextSetString 30c 0
#pragma libcall XtBase XmTextSetTopCharacter 312 0
#pragma libcall XtBase XmToggleButtonGadgetSetState 318 0
#pragma libcall XtBase XmToggleButtonSetState 31e 0
#pragma libcall XtBase XmToggleButtonGadgetGetState 324 0
#pragma libcall XtBase XmToggleButtonGetState 32a 0
#pragma libcall XtBase XmUpdateDisplay 330 0
#pragma libcall XtBase _XmStrings 336 0
#pragma libcall XtBase xmCascadeButtonWidgetClass 33c 0
#pragma libcall XtBase xmDrawingAreaWidgetClass 342 0
#pragma libcall XtBase xmFrameWidgetClass 348 0
#pragma libcall XtBase xmLabelGadgetClass 34e 0
#pragma libcall XtBase xmLabelWidgetClass 354 0
#pragma libcall XtBase xmPushButtonGadgetClass 35a 0
#pragma libcall XtBase xmPushButtonWidgetClass 360 0
#pragma libcall XtBase xmRowColumnWidgetClass 366 0
#pragma libcall XtBase xmScaleWidgetClass 36c 0
#pragma libcall XtBase xmScrolledWindowWidgetClass 372 0
#pragma libcall XtBase xmSeparatorGadgetClass 378 0
#pragma libcall XtBase xmTextFieldWidgetClass 37e 0
#pragma libcall XtBase xmTextWidgetClass 384 0
#pragma libcall XtBase xmToggleButtonGadgetClass 38a 0
#pragma libcall XtBase nonl 390 0
#pragma libcall XtBase pclose 396 0
#pragma libcall XtBase popen 39c 0
#pragma libcall XtBase select 3a2 0
#pragma libcall XtBase XVisualIDFromVisual 3a8 801
#pragma libcall XtBase XInternAtom 3ae 19803
#pragma libcall XtBase XQueryTree 3b4 DCBA9806
#pragma libcall XtBase XGetWindowProperty 3ba EDCBA54321980C
#pragma libcall XtBase erf 3c0 101
#pragma libcall XtBase erfc 3c6 101
#pragma libcall XtBase lgamma 3cc 101
#pragma libcall XtBase XKeysymToKeycode 3d2 1802
#pragma libcall XtBase XSetWindowBackground 3d8 0
#pragma libcall XtBase XUngrabPointer 3de 0
#pragma libcall XtBase XSetWindowBackgroundPixmap 3e4 0
#pragma libcall XtBase getwd 3ea 0
#pragma libcall XtBase XUngrabServer 3f0 0
#pragma libcall XtBase XTranslateCoordinates 3f6 0
#pragma libcall XtBase XMoveResizeWindow 3fc 0
#pragma libcall XtBase getpwnam 402 0
#pragma libcall XtBase umask 408 0
#pragma libcall XtBase XCheckTypedWindowEvent 40e 0
#pragma libcall XtBase XGrabButton 414 0
#pragma libcall XtBase XGrabPointer 41a 0
#pragma libcall XtBase XSetTransientForHint 420 0
#pragma libcall XtBase XSetCloseDownMode 426 0
#pragma libcall XtBase XGetGeometry 42c 0
#pragma libcall XtBase XTextWidth 432 0
#pragma libcall XtBase XDeleteProperty 438 0
#pragma libcall XtBase XGrabServer 43e 0
#pragma libcall XtBase random 444 0
#pragma libcall XtBase XRaiseWindow 44a 0
#pragma libcall XtBase XDestroyRegion 450 0
#pragma libcall XtBase endpwent 456 0
#pragma libcall XtBase XStoreBytes 45c 0
#pragma libcall XtBase XClipBox 462 0
#pragma libcall XtBase XSetState 468 0
#pragma libcall XtBase XCreateRegion 46e 0
#pragma libcall XtBase XSetSubwindowMode 474 0
#pragma libcall XtBase XUnionRectWithRegion 47a 0
#pragma libcall XtBase XGetNormalHints 480 0
#pragma libcall XtBase XUngrabButton 486 0
#pragma libcall XtBase XSetRegion 48c 0
#pragma libcall XtBase XCheckWindowEvent 492 0
#pragma libcall XtBase mknod 498 0
#pragma libcall XtBase XSendEvent 49e 0
#pragma libcall XtBase XKillClient 4a4 0
#pragma libcall XtBase getuid 4aa 0
#pragma libcall XtBase RWGetMsg 4b0 0
#pragma libcall XtBase XCopyGC 4b6 0
#pragma libcall XtBase XpmCreatePixmapFromData 4bc 0
#pragma libcall XtBase RWtableGetEntry 4c2 0
#pragma libcall XtBase RWtableGetWriterList 4c8 0
#pragma libcall XtBase XawToggleGetCurrent 4ce 0
#pragma libcall XtBase XawListChange 4d4 0
#pragma libcall XtBase RWtableGetReaderID 4da 0
#pragma libcall XtBase XawToggleSetCurrent 4e0 0
#pragma libcall XtBase XShapeCombineMask 4e6 0
#pragma libcall XtBase getpwuid 4ec 0
#pragma libcall XtBase RWtableGetWriter 4f2 0
#pragma libcall XtBase XAllowEvents 4f8 0
#pragma libcall XtBase XawListShowCurrent 4fe 0
#pragma libcall XtBase RWtableGetId 504 0
#pragma libcall XtBase WriteAsciiPNMfd 50a 0
#pragma libcall XtBase RWtableGetReader 510 0
#pragma libcall XtBase XawTextSinkSetTabs 516 0
#pragma libcall XtBase XQueryColor 51c 0
#pragma libcall XtBase XawListHighlight 522 0
#pragma libcall XtBase XawScrollbarSetThumb 528 0
#pragma libcall XtBase XawToggleUnsetCurrent 52e 0
#pragma libcall XtBase RWtableGetReaderList 534 0
#pragma libcall XtBase XResourceManagerString 53a 0
#pragma libcall XtBase XSetSelectionOwner 540 0
#pragma libcall XtBase hypot 546 2102
#pragma libcall XtBase cfree 54c 801
#pragma libcall XtBase XSetIOErrorHandler 552 0
#pragma libcall XtBase XTextExtents 558 0
#pragma libcall XtBase listWidgetClass 55e 0
#pragma libcall XtBase XPutBackEvent 564 0
#pragma libcall XtBase XawFormDoLayout 56a 0
#pragma libcall XtBase getpid 570 0
#pragma libcall XtBase XLookupKeysym 576 0
#pragma libcall XtBase XGeometry 57c 0
#pragma libcall XtBase XDefaultDepthOfScreen 582 0
#pragma libcall XtBase boxWidgetClass 588 0
#pragma libcall XtBase XUnloadFont 58e 0
#pragma libcall XtBase XSetWMProtocols 594 0
#pragma libcall XtBase XawTextReplace 59a 0
#pragma libcall XtBase transientShellWidgetClass 5a0 0
#pragma libcall XtBase XGetFontProperty 5a6 0
#pragma libcall XtBase FMT8BIT 5ac 0
#pragma libcall XtBase labelWidgetClass 5b2 0
#pragma libcall XtBase XFreeFontNames 5b8 0
#pragma libcall XtBase viewportWidgetClass 5be 0
#pragma libcall XtBase geteuid 5c4 0
#pragma libcall XtBase smeBSBObjectClass 5ca 0
#pragma libcall XtBase XStringToKeysym 5d0 0
#pragma libcall XtBase toggleWidgetClass 5d6 0
#pragma libcall XtBase XListFonts 5dc 0
#pragma libcall XtBase XGetWMHints 5e2 0
#pragma libcall XtBase commandWidgetClass 5e8 0
#pragma libcall XtBase XCopyColormapAndFree 5ee 0
#pragma libcall XtBase formWidgetClass 5f4 0
#pragma libcall XtBase XawTextSetInsertionPoint 5fa 0
#pragma libcall XtBase asciiTextWidgetClass 600 0
#pragma libcall XtBase XDefaultRootWindow 606 0
#pragma libcall XtBase scrollbarWidgetClass 60c 0
#pragma libcall XtBase menuButtonWidgetClass 612 0
#pragma libcall XtBase XWriteBitmapFile 618 0
#pragma libcall XtBase XSetTSOrigin 61e 0
#pragma libcall XtBase simpleMenuWidgetClass 624 0
#pragma libcall XtBase XGetGCValues 62a 0
#pragma libcall XtBase XLookUpAssoc 630 0
#pragma libcall XtBase XCreateAssocTable 636 0
#pragma libcall XtBase XUnmapSubwindows 63c 0
#pragma libcall XtBase XMakeAssoc 642 0
#pragma libcall XtBase execl 648 0
#pragma libcall XtBase fork 64e 0
#pragma libcall XtBase flock 654 0
#pragma libcall XtBase getlogin 65a 0
#pragma libcall XtBase mpthd_switch 660 0
#pragma libcall XtBase mpthd_me_reg 666 0
#pragma libcall XtBase mpthd_init 66c 0
#pragma libcall XtBase mpthd_setup 672 0
#pragma libcall XtBase XmFontListCreate 678 0
#pragma libcall XtBase XLoadFont 67e 9802
#pragma libcall XtBase XLoadQueryFont 684 9802
#pragma libcall XtBase XFreeFont 68a 9802
#pragma libcall XtBase XSetFont 690 A9803
