/*
 *  This file is part of ixemul.library for the Amiga.
 *  Copyright (C) 1991, 1992  Markus M. Wild
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public
 *  License along with this library; if not, write to the Free
 *  Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _SYS_SYSCALL_H
#define _SYS_SYSCALL_H

/* Amiga - */
#define SYS_abort     1  
#define SYS_abs     2  
#define SYS_access     3  
#define SYS_alarm     4  
#define SYS_atexit     5  
#define SYS_atof     6  
#define SYS_atoi     7  
#define SYS_atol     8  
#define SYS_bcmp     9  
#define SYS_bcopy     10  
#define SYS_bsearch     11  
#define SYS_bzero     12  
#define SYS_calloc     13  
#define SYS_cfgetispeed     14  
#define SYS_cfgetospeed     15  
#define SYS_cfmakeraw     16  
#define SYS_cfree     17  
#define SYS_cfsetispeed     18  
#define SYS_cfsetospeed     19  
#define SYS_cfsetspeed     20  
#define SYS_chdir     21  
#define SYS_chmod     22  
#define SYS_chown     23  
#define SYS_clock     24  
#define SYS_close     25  
#define SYS_creat     26  
#define SYS___must_recompile27     27  
#define SYS___must_recompile28     28  
#define SYS___must_recompile29     29  
#define SYS___must_recompile30     30  
#define SYS___must_recompile31     31  
#define SYS___must_recompile32     32  
#define SYS___must_recompile33     33  
#define SYS___must_recompile34     34  
#define SYS_difftime     35  
#define SYS___obsolete_div     36  
#define SYS_dup     37  
#define SYS_dup2     38  
#define SYS_exit     39  
#define SYS_fchmod     40  
#define SYS_fcntl     41  
#define SYS_ffs     42  
#define SYS_flock     43  
#define SYS_free     44  
#define SYS_frexp     45  
#define SYS_fstat     46  
#define SYS_fsync     47  
#define SYS_ftime     48  
#define SYS_ftruncate     49  
#define SYS_getcwd     50  
#define SYS_getdtablesize     51  
#define SYS_getegid     52  
#define SYS_getenv     53  
#define SYS_geteuid     54  
#define SYS_getgid     55  
#define SYS_getgrgid     56  
#define SYS_getgroups     57  
#define SYS_gethostname     58  
#define SYS_getitimer     59  
#define SYS_getpagesize     60  
#define SYS_getpgrp     61  
#define SYS_getpid     62  
#define SYS_getppid     63  
#define SYS_getpriority     64  
#define SYS_getpwnam     65  
#define SYS_getpwuid     66  
#define SYS_getrlimit     67  
#define SYS_getrusage     68  
#define SYS_gettimeofday     69  
#define SYS_getuid     70  
#define SYS_getwd     71  
#define SYS_index     72  
#define SYS_initgroups     73  
#define SYS_insque     74  
#define SYS_ioctl     75  
#define SYS_isalnum     76  
#define SYS_isalpha     77  
#define SYS_isatty     78  
#define SYS_iscntrl     79  
#define SYS_isdigit     80  
#define SYS_isgraph     81  
#define SYS_islower     82  
#define SYS_isprint     83  
#define SYS_ispunct     84  
#define SYS_isspace     85  
#define SYS_isupper     86  
#define SYS_isxdigit     87  
#define SYS_ix_startup     88  
#define SYS_kill     89  
#define SYS_killpg     90  
#define SYS_labs     91  
#define SYS___obsolete_ldiv     92  
#define SYS_link     93  
#define SYS_longjmp     94  
#define SYS_longjmperror     95  
#define SYS_lseek     96  
#define SYS_lstat     97  
#define SYS_malloc     98  
#define SYS_memalign     99  
#define SYS_memccpy     100  
#define SYS_memchr     101  
#define SYS_memcmp     102  
#define SYS_memcpy     103  
#define SYS_memmove     104  
#define SYS_memset     105  
#define SYS_mkdir     106  
#define SYS_mkstemp     107  
#define SYS_mktemp     108  
#define SYS_open     109  
#define SYS_pause     110  
#define SYS_perror     111  
#define SYS_pipe     112  
#define SYS_psig     113  
#define SYS_psignal     114  
#define SYS_putenv     115  
#define SYS_qsort     116  
#define SYS_rand     117  
#define SYS_random     118  
#define SYS_read     119  
#define SYS_readlink     120  
#define SYS_readv     121  
#define SYS_realloc     122  
#define SYS_remove     123  
#define SYS_remque     124  
#define SYS_rename     125  
#define SYS_rindex     126  
#define SYS_rmdir     127  
#define SYS_select     128  
#define SYS_setenv     129  
#define SYS_setgroups     130  
#define SYS_sethostname     131  
#define SYS_setitimer     132  
#define SYS_setjmp     133  
#define SYS_setpgrp     134  
#define SYS_setpriority     135  
#define SYS_setrlimit     136  
#define SYS_settimeofday     137  
#define SYS_sigaction     138  
#define SYS_sigaddset     139  
#define SYS_sigblock     140  
#define SYS_sigdelset     141  
#define SYS_sigemptyset     142  
#define SYS_sigfillset     143  
#define SYS_siginterrupt     144  
#define SYS_sigismember     145  
#define SYS_siglongjmp     146  
#define SYS_signal     147  
#define SYS_sigpause     148  
#define SYS_sigpending     149  
#define SYS_sigprocmask     150  
#define SYS_sigreturn     151  
#define SYS_sigsetjmp     152  
#define SYS_sigsetmask     153  
#define SYS_sigstack     154  
#define SYS_sigsuspend     155  
#define SYS_sigvec     156  
#define SYS_sleep     157  
#define SYS_srand     158  
#define SYS_srandom     159  
#define SYS_stat     160  
#define SYS_strcasecmp     161  
#define SYS_strcat     162  
#define SYS_strchr     163  
#define SYS_strcmp     164  
#define SYS_strcoll     165  
#define SYS_strcpy     166  
#define SYS_strcspn     167  
#define SYS_strdup     168  
#define SYS_strerror     169  
#define SYS_strftime     170  
#define SYS_strlen     171  
#define SYS_strmode     172  
#define SYS_strncasecmp     173  
#define SYS_strncat     174  
#define SYS_strncmp     175  
#define SYS_strncpy     176  
#define SYS_strpbrk     177  
#define SYS_strrchr     178  
#define SYS_strsep     179  
#define SYS_strspn     180  
#define SYS_strstr     181  
#define SYS_strtok     182  
#define SYS_strtol     183  
#define SYS_strtoul     184  
#define SYS_strunvis     185  
#define SYS_strvis     186  
#define SYS_strvisx     187  
#define SYS_strxfrm     188  
#define SYS_swab     189  
#define SYS_symlink     190  
#define SYS_system     191  
#define SYS_tcgetattr     192  
#define SYS_tcgetpgrp     193  
#define SYS_tcsetattr     194  
#define SYS_tcsetpgrp     195  
#define SYS_time     196  
#define SYS_tmpnam     197  
#define SYS_tolower     198  
#define SYS_toupper     199  
#define SYS_truncate     200  
#define SYS_ualarm     201  
#define SYS_umask     202  
#define SYS_unlink     203  
#define SYS_unvis     204  
#define SYS_usleep     205  
#define SYS_utime     206  
#define SYS_utimes     207  
#define SYS_valloc     208  
#define SYS_vis     209  
#define SYS_write     210  
#define SYS_writev     211  
#define SYS__exit     212  
#define SYS__longjmp     213  
#define SYS__setjmp     214  
#define SYS___must_recompile215     215  
#define SYS___must_recompile216     216  
#define SYS___must_recompile217     217  
#define SYS___adddf3     218  
#define SYS___addsf3     219  
#define SYS___must_recompile220     220  
#define SYS___must_recompile221     221  
#define SYS___must_recompile222     222  
#define SYS___must_recompile223     223  
#define SYS___must_recompile224     224  
#define SYS___cmpdf2     225  
#define SYS___must_recompile226     226  
#define SYS___cmpsf2     227  
#define SYS___divdf3     228  
#define SYS___must_recompile229     229  
#define SYS___divsf3     230  
#define SYS___divsi3     231  
#define SYS___eqdf2     232  
#define SYS___eqsf2     233  
#define SYS___extendsfdf2     234  
#define SYS___must_recompile235     235  
#define SYS___fixdfsi     236  
#define SYS___must_recompile237     237  
#define SYS___fixsfsi     238  
#define SYS___must_recompile239     239  
#define SYS___must_recompile240     240  
#define SYS___must_recompile241     241  
#define SYS___must_recompile242     242  
#define SYS___must_recompile243     243  
#define SYS___must_recompile244     244  
#define SYS___floatsidf     245  
#define SYS___floatsisf     246  
#define SYS___gedf2     247  
#define SYS___gesf2     248  
#define SYS___gtdf2     249  
#define SYS___gtsf2     250  
#define SYS___ledf2     251  
#define SYS___lesf2     252  
#define SYS___must_recompile253     253  
#define SYS___must_recompile254     254  
#define SYS___must_recompile255     255  
#define SYS___must_recompile256     256  
#define SYS___ltdf2     257  
#define SYS___ltsf2     258  
#define SYS___must_recompile259     259  
#define SYS___modsi3     260  
#define SYS___muldf3     261  
#define SYS___must_recompile262     262  
#define SYS___mulsf3     263  
#define SYS___mulsi3     264  
#define SYS___nedf2     265  
#define SYS___negdf2     266  
#define SYS___must_recompile267     267  
#define SYS___negsf2     268  
#define SYS___nesf2     269  
#define SYS___subdf3     270  
#define SYS___subsf3     271  
#define SYS___truncdfsf2     272  
#define SYS___must_recompile273     273  
#define SYS___must_recompile274     274  
#define SYS___must_recompile275     275  
#define SYS___udivsi3     276  
#define SYS___must_recompile277     277  
#define SYS___umodsi3     278  
#define SYS___must_recompile279     279  
#define SYS_modf     280  
#define SYS_opendir     281  
#define SYS_readdir     282  
#define SYS_rewinddir     283  
#define SYS_closedir     284  
#define SYS_telldir     285  
#define SYS_seekdir     286  
#define SYS___obsolete_ssystem     287  
#define SYS_isinf     288  
#define SYS_isnan     289  
#define SYS_ldexp     290  
#define SYS_ix_chmod     291  
#define SYS_stricmp     292  
#define SYS_strnicmp     293  
#define SYS_atan     294  
#define SYS_sin     295  
#define SYS_cos     296  
#define SYS_tan     297  
#define SYS_sincos     298  
#define SYS_sinh     299  
#define SYS_cosh     300  
#define SYS_tanh     301  
#define SYS_exp     302  
#define SYS_log     303  
#define SYS_pow     304  
#define SYS_sqrt     305  
#define SYS_asin     306  
#define SYS_acos     307  
#define SYS_log10     308  
#define SYS_fabs     309  
#define SYS_initstate     310  
#define SYS_setstate     311  
#define SYS_ix_exec_entry     312  
#define SYS_ix_get_vars     313  
#define SYS_execve     314  
#define SYS_execl     315  
#define SYS_execv     316  
#define SYS_execle     317  
#define SYS_execlp     318  
#define SYS_execvp     319  
#define SYS_ix_vfork     320  
#define SYS_wait4     321  
#define SYS_wait     322  
#define SYS_wait3     323  
#define SYS_waitpid     324  
#define SYS_ix_vfork_resume     325  
#define SYS_profil     326  
#define SYS_ptrace     327  
#define SYS_clearerr     328  
#define SYS_fclose     329  
#define SYS_fdopen     330  
#define SYS_feof     331  
#define SYS_ferror     332  
#define SYS_fflush     333  
#define SYS_fgetc     334  
#define SYS_fgetln     335  
#define SYS_fgetpos     336  
#define SYS_fgets     337  
#define SYS_fileno     338  
#define SYS_f_prealloc     339  
#define SYS_fopen     340  
#define SYS_fprintf     341  
#define SYS_fpurge     342  
#define SYS_fputc     343  
#define SYS_fputs     344  
#define SYS_fread     345  
#define SYS_freopen     346  
#define SYS_fscanf     347  
#define SYS_fseek     348  
#define SYS_fsetpos     349  
#define SYS_ftell     350  
#define SYS_funopen     351  
#define SYS_fwrite     352  
#define SYS_getc     353  
#define SYS_getchar     354  
#define SYS_gets     355  
#define SYS_getw     356  
#define SYS_printf     357  
#define SYS_putc     358  
#define SYS_putchar     359  
#define SYS_puts     360  
#define SYS_putw     361  
#define SYS_rewind     362  
#define SYS_scanf     363  
#define SYS_setbuf     364  
#define SYS_setbuffer     365  
#define SYS_setlinebuf     366  
#define SYS_setvbuf     367  
#define SYS_snprintf     368  
#define SYS_sprintf     369  
#define SYS_sscanf     370  
#define SYS_tempnam     371  
#define SYS_tmpfile     372  
#define SYS_ungetc     373  
#define SYS_vfprintf     374  
#define SYS_vprintf     375  
#define SYS_vscanf     376  
#define SYS_vsnprintf     377  
#define SYS_vsprintf     378  
#define SYS_vsscanf     379  
#define SYS_crypt     380  
#define SYS_des_cipher     381  
#define SYS_des_setkey     382  
#define SYS_encrypt     383  
#define SYS_setkey     384  
#define SYS_fnmatch     385  
#define SYS___must_recompile386     386  
#define SYS___must_recompile387     387  
#define SYS___must_recompile388     388  
#define SYS___must_recompile389     389  
#define SYS___must_recompile390     390  
#define SYS_cuserid     391  
#define SYS_getlogin     392  
#define SYS_glob     393  
#define SYS_globfree     394  
#define SYS_ix_filehandle     395  
#define SYS_times     396  
#define SYS_mblen     397  
#define SYS_mbstowcs     398  
#define SYS_mbtowc     399  
#define SYS_wcstombs     400  
#define SYS_wctomb     401  
#define SYS_heapsort     402  
#define SYS_radixsort     403  
#define SYS___sflush     404  
#define SYS___slbexpand     405  
#define SYS___sfp     406  
#define SYS___sflags     407  
#define SYS___sfvwrite     408  
#define SYS___smakebuf     409  
#define SYS___srefill     410  
#define SYS___srget     411  
#define SYS___sclose     412  
#define SYS___sread     413  
#define SYS___sseek     414  
#define SYS___swrite     415  
#define SYS___svfscanf     416  
#define SYS___swbuf     417  
#define SYS___swsetup     418  
#define SYS_fchdir     419  
#define SYS_strtod     420  
#define SYS_setgrent     421  
#define SYS_getgrent     422  
#define SYS_endgrent     423  
#define SYS_ix_resident     424  
#define SYS_ix_geta4     425  
#define SYS_ix_check_cpu     426  
#define SYS_ix_tracecntl     427  
#define SYS_sysconf     428  
#define SYS_pathconf     429  
#define SYS_fpathconf     430  
#define SYS_getfsstat     431  
#define SYS_fstatfs     432  
#define SYS_statfs     433  
#define SYS_getmntinfo     434  
#define SYS_getgrnam     435  
#define SYS_endpwent     436  
#define SYS_sync     437  
#define SYS_fork     438  
#define SYS_mkfifo     439  
#define SYS_mknod     440  
#define SYS_setuid     441  
#define SYS_nice     442  
#define SYS_floor     443  
#define SYS_ceil     444  
#define SYS_setgid     445  
#define SYS_vfork     446  
#define SYS___must_recompile447     447  
#define SYS___must_recompile448     448  
#define SYS___must_recompile449     449  
#define SYS___must_recompile450     450  
#define SYS_connect     451  
#define SYS_sendto     452  
#define SYS_send     453  
#define SYS_sendmsg     454  
#define SYS_recvfrom     455  
#define SYS_recv     456  
#define SYS_recvmsg     457  
#define SYS_shutdown     458  
#define SYS_setsockopt     459  
#define SYS_getsockopt     460  
#define SYS_getsockname     461  
#define SYS_getpeername     462  
#define SYS_unsetenv     463  
#define SYS_socket     464  
#define SYS_bind     465  
#define SYS_listen     466  
#define SYS_accept     467  
#define SYS_tcdrain     468  
#define SYS_tcflush     469  
#define SYS_tcflow     470  
#define SYS_tcsendbreak     471  
#define SYS_raise     472  
#define SYS_ix_get_gmt_offset     473  
#define SYS_ix_set_gmt_offset     474  
#define SYS_ix_get_default_settings     475  
#define SYS_ix_get_settings     476  
#define SYS_ix_set_settings     477  
#define SYS_uname     478  
#define SYS_socketpair    479  
#define SYS___init_stk_limit     480  
#define SYS___stkovf     481  
#define SYS___stkext     482  
#define SYS___stkext_f     483  
#define SYS___stkrst     484  
#define SYS_inet_addr    485  
#define SYS_inet_aton    486  
#define SYS_inet_lnaof    487  
#define SYS___obsolete_inet_makeaddr    488  
#define SYS_inet_netof    489  
#define SYS_inet_network    490  
#define SYS_inet_ntoa    491  
#define SYS_gethostbyname    492  
#define SYS_gethostbyaddr    493  
#define SYS_getnetbyname    494  
#define SYS_getnetbyaddr    495  
#define SYS_setnetent    496  
#define SYS_endnetent    497  
#define SYS_getnetent    498  
#define SYS_setservent    499  
#define SYS_endservent    500  
#define SYS_getservent    501  
#define SYS___must_recompile502    502  
#define SYS___must_recompile503    503  
#define SYS___must_recompile504    504  
#define SYS___must_recompile505    505  
#define SYS___must_recompile506    506  
#define SYS___must_recompile507    507  
#define SYS_setgroupent    508  
#define SYS_setpassent    509  
#define SYS_herror    510  
#define SYS_getservbyname    511  
#define SYS_getservbyport    512  
#define SYS_setpwent    513  
#define SYS_getpwent    514  
#define SYS_getprotoent    515  
#define SYS_getprotobyname    516  
#define SYS_getprotobynumber    517  
#define SYS_setprotoent    518  
#define SYS_endprotoent    519  
#define SYS___must_recompile520    520  
#define SYS___must_recompile521    521  
#define SYS_getpass    522  
#define SYS___must_recompile523    523  
#define SYS___must_recompile524    524  
#define SYS___must_recompile525    525  
#define SYS___must_recompile526    526  
#define SYS___must_recompile527    527  
#define SYS___must_recompile528    528  
#define SYS___must_recompile529    529  
#define SYS___must_recompile530    530  
#define SYS_sethostent    531  
#define SYS_endhostent    532  
#define SYS_gethostid    533  
#define SYS_vsyslog    534  
#define SYS_openlog    535  
#define SYS_closelog    536  
#define SYS_syslog    537  
#define SYS_setlogmask    538  
#define SYS_issig    539  
#define SYS_setrun    540  
#define SYS_seteuid    541  
#define SYS_setegid    542  
#define SYS_setreuid    543  
#define SYS_setregid    544  
#define SYS_chroot    545  
#define SYS_fchown    546  
#define SYS_getusershell    547  
#define SYS_setusershell    548  
#define SYS_endusershell    549  
#define SYS__getlogin    550  
#define SYS__psignal    551  
#define SYS_falloc    552  
#define SYS__set_socket_params    553  
#define SYS_setsid    554  
#define SYS_getdomainname    555  
#define SYS_setlogin     556  
#define SYS_isblank     557  
#define SYS_mmap     558  
#define SYS_munmap     559  
#define SYS_mlock     560  
#define SYS_munlock     561  
#define SYS_madvise     562  
#define SYS_mprotect     563  
#define SYS_msync     564  
#define SYS_setlocale     565  
#define SYS_localeconv     566  
#define SYS_strtoq     567  
#define SYS_strtouq     568  
#define SYS_setpgid     569  
#define SYS___must_recompile570     570  
#define SYS___stkext_startup     571  
#define SYS_div    572  
#define SYS_ldiv    573  
#define SYS_inet_makeaddr    574  
#define SYS_popen    575  
#define SYS_pclose    576  
#define SYS_shmat    577  
#define SYS_shmdt    578  
#define SYS_shmget    579  
#define SYS_shmctl    580  
#define SYS_ix_req    581  
#define SYS_ix_select    582  
#define SYS_isascii    583  
#define SYS_isiso    584  
#define SYS_toascii    585  
#define SYS_toiso    586  
#define SYS_ix_get_first_segment    587  
#define SYS_ix_get_next_segment    588  
#define SYS_hstrerror    589  
#define SYS_ix_obtain_socket    590  
#define SYS_ix_release_socket    591  
#define SYS___flush_cache    592  
#define SYS_ix_flush_insn_cache    593  
#define SYS_ix_flush_caches    594  
#define SYS_ix_get_long    595  
#define SYS_ix_set_long    596  
#define SYS_ix_flush_data_cache    597  
#define SYS_ix_mutex_lock    598  
#define SYS_ix_mutex_attempt_lock    599  
#define SYS_ix_mutex_unlock    600  
#define SYS_semop    601  
#define SYS_semctl    602  
#define SYS_semget    603  
#define SYS_msgget    604  
#define SYS_msgctl    605  
#define SYS_msgrcv    606  
#define SYS_msgsnd    607  
#define SYS___ix_get_environ    608  
#define SYS___ix_cli_parse    609  
#define SYS___ix_wb_parse    610  
#define SYS___ix_install_sigwinch    611  
#define SYS___ix_remove_sigwinch    612  
#define SYS___ix_init_ids    613


#ifndef _KERNEL
extern void *ixemulbase;


#define syscall(vec, args...) \
  ({register int (*_sc)()=(void *)(&((char *)ixemulbase)[-((vec)+4)*6]); _sc(args);})
#endif

#endif /* _SYS_SYSCALL_H */
